version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data_user_service:/var/lib/postgresql/data/
    env_file:
      - ./services/database/.env
    ports:
      - 5432:5432 
    restart: always

  blog-user-management-service:
    build:
      context: services/web
      dockerfile: Dockerfile.prod
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./services/web/.env
    depends_on:
      - db
      - redis
    restart: always

  celery-worker:
    build:
      context: services/web
      dockerfile: Dockerfile.prod
    command: celery --app manage.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./services/web/.env
    depends_on:
      - blog-user-management-service
      - redis
    restart: always

  redis:
    image: redis:6-alpine
    restart: always

volumes:
  postgres_data_user_service:
