version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data_sql:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5436:5432

volumes:
  postgres_data_sql:
