"""creates the report

Revision ID: 5fcf3636d198
Revises: f6a7dc512ce2
Create Date: 2022-10-16 11:01:04.348133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcf3636d198'
down_revision = 'f6a7dc512ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
