"""creates the report

Revision ID: 7ed31d4896aa
Revises: ec861ebd7a4e
Create Date: 2022-10-16 10:30:25.679826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed31d4896aa'
down_revision = 'ec861ebd7a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('date_flagged', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags')
    # ### end Alembic commands ###
